# Generated by Django 5.0.3 on 2024-04-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anio',
            name='anio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='numero',
            name='numero',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volumen',
            name='volumen',
            field=models.CharField(max_length=100),
        ),
    ]
