# Generated by Django 5.0.3 on 2024-04-23 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0003_alter_article_identifier_url_alter_article_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='anio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='harvest.anio'),
        ),
        migrations.AlterField(
            model_name='article',
            name='numero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='harvest.numero'),
        ),
        migrations.AlterField(
            model_name='article',
            name='volumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='harvest.volumen'),
        ),
    ]
