# Generated by Django 5.0.3 on 2024-04-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0004_alter_article_anio_alter_article_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subject',
            field=models.TextField(null=True),
        ),
    ]
