# Generated by Django 5.0.3 on 2024-04-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0005_article_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='anios',
            field=models.ManyToManyField(null=True, to='harvest.anio'),
        ),
    ]
