# Generated by Django 5.0.3 on 2024-04-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0006_proveedor_anios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='anios',
        ),
    ]
