# Generated by Django 5.0.3 on 2024-04-29 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0007_remove_proveedor_anios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subclasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.clasificacion')),
            ],
        ),
    ]
