# Generated by Django 5.0.3 on 2024-04-29 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0008_subclasificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revista',
            name='clasificacion',
        ),
        migrations.AddField(
            model_name='revista',
            name='subclasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='harvest.subclasificacion'),
        ),
    ]
