# Generated by Django 5.0.3 on 2024-05-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0010_alter_article_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revista',
            name='subclasificacion',
        ),
        migrations.AddField(
            model_name='revista',
            name='subclasificacion',
            field=models.ManyToManyField(to='harvest.subclasificacion'),
        ),
    ]
