# Generated by Django 5.0.3 on 2024-05-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0011_remove_revista_subclasificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataformat',
            name='prefix',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_spec',
            field=models.CharField(max_length=255),
        ),
    ]
