# Generated by Django 5.0.3 on 2024-05-26 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0013_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdiomaR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='revista',
            name='idioma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='harvest.idiomar'),
        ),
    ]
