# Generated by Django 5.0.3 on 2024-05-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0014_idiomar_alter_revista_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='identifier_url',
            field=models.URLField(max_length=1000000),
        ),
    ]
