# Generated by Django 5.0.3 on 2024-05-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0015_alter_article_identifier_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='relation',
            field=models.URLField(max_length=999999),
        ),
    ]
