# Generated by Django 5.0.3 on 2024-05-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0016_alter_article_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos_a_actualizar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
